name: HT-Announcement
version: 1.0.0
main: com.mustafa8907.htannouncement.HTAnnouncementPlugin
author: mustafa8907
api-version: 1.13
commands:
  announcement:
    description: Ana komut
    aliases: [ann, duyuru]
    permission: htannouncement.use
